#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum WeaponKind {
    Melee,
    Pistol,
    Smg,
    Shotgun,
    Rifle,
    Launcher,
    Sxs, // side-by-side (break-action) shotgun
}

impl WeaponKind {
    /// Stable slot index for per-kind weapon visuals.
    pub fn index(self) -> usize {
        match self {
            WeaponKind::Melee => 0,
            WeaponKind::Pistol => 1,
            WeaponKind::Smg => 2,
            WeaponKind::Shotgun => 3,
            WeaponKind::Rifle => 4,
            WeaponKind::Launcher => 5,
            WeaponKind::Sxs => 6,
        }
    }
}

/// Number of distinct weapon-kind visual slots.
pub const WEAPON_KINDS: usize = 7;

#[derive(Clone, Copy, PartialEq, Eq, Debug, Hash)]
pub enum Ammo {
    None,
    Rounds,
    Shells,
    Rockets,
}

#[derive(Clone, Copy)]
pub struct Weapon {
    pub name: &'static str,
    pub kind: WeaponKind,
    pub damage: f32,
    /// Shots per second.
    pub rate: f32,
    pub auto: bool,
    pub clip: i32,
    pub reload: f32,
    pub pellets: u32,
    pub spread: f32,
    pub range: f32,
    pub speed: f32,
    pub knockback: f32,
    pub sever: f32,
    pub explosive: f32, // blast radius, 0 = none
    pub ammo: Ammo,
    pub reach: f32, // melee reach
    // Ballistics: small calibres ricochet off walls; big powerful rounds punch
    // through targets and even walls, losing killing power each time.
    pub ricochet: u32,    // wall bounces before the round dies
    pub pierce: i32,      // extra targets the round passes through
    pub wall_pierce: u32, // walls the round punches through
    pub falloff: f32,     // damage retained per ricochet / penetration
}

pub const WEAPONS: &[Weapon] = &[
    Weapon {
        name: "Knife",
        kind: WeaponKind::Melee,
        damage: 34.0,
        rate: 3.2,
        auto: false,
        clip: 0,
        reload: 0.0,
        pellets: 1,
        spread: 0.0,
        range: 0.0,
        speed: 0.0,
        knockback: 60.0,
        sever: 0.25,
        explosive: 0.0,
        ammo: Ammo::None,
        reach: 26.0,
        ricochet: 0,
        pierce: 0,
        wall_pierce: 0,
        falloff: 1.0,
    },
    Weapon {
        name: "Bat",
        kind: WeaponKind::Melee,
        damage: 52.0,
        rate: 1.9,
        auto: false,
        clip: 0,
        reload: 0.0,
        pellets: 1,
        spread: 0.0,
        range: 0.0,
        speed: 0.0,
        knockback: 220.0,
        sever: 0.08,
        explosive: 0.0,
        ammo: Ammo::None,
        reach: 30.0,
        ricochet: 0,
        pierce: 0,
        wall_pierce: 0,
        falloff: 1.0,
    },
    Weapon {
        name: "9mm Pistol",
        kind: WeaponKind::Pistol,
        damage: 26.0,
        rate: 5.0,
        auto: false,
        clip: 12,
        reload: 1.1,
        pellets: 1,
        spread: 0.02,
        range: 520.0,
        speed: 940.0,
        knockback: 70.0,
        sever: 0.04,
        explosive: 0.0,
        ammo: Ammo::Rounds,
        reach: 0.0,
        ricochet: 1,
        pierce: 0,
        wall_pierce: 0,
        falloff: 0.8,
    },
    Weapon {
        name: "Machine Gun",
        kind: WeaponKind::Smg,
        damage: 17.0,
        rate: 12.0,
        auto: true,
        clip: 32,
        reload: 1.6,
        pellets: 1,
        spread: 0.09,
        range: 480.0,
        speed: 900.0,
        knockback: 45.0,
        sever: 0.03,
        explosive: 0.0,
        ammo: Ammo::Rounds,
        reach: 0.0,
        ricochet: 1,
        pierce: 0,
        wall_pierce: 0,
        falloff: 0.85,
    },
    Weapon {
        name: "Pump Shotgun",
        kind: WeaponKind::Shotgun,
        damage: 15.0,
        rate: 1.3,
        auto: false,
        clip: 6,
        reload: 2.2,
        pellets: 8,
        spread: 0.20,
        range: 320.0,
        speed: 820.0,
        knockback: 160.0,
        sever: 0.14,
        explosive: 0.0,
        ammo: Ammo::Shells,
        reach: 0.0,
        ricochet: 1,
        pierce: 0,
        wall_pierce: 0,
        falloff: 0.7,
    },
    Weapon {
        name: "Assault Rifle",
        kind: WeaponKind::Rifle,
        damage: 24.0,
        rate: 9.0,
        auto: true,
        clip: 30,
        reload: 1.8,
        pellets: 1,
        spread: 0.05,
        range: 640.0,
        speed: 1050.0,
        knockback: 60.0,
        sever: 0.06,
        explosive: 0.0,
        ammo: Ammo::Rounds,
        reach: 0.0,
        ricochet: 0,
        pierce: 2,
        wall_pierce: 1,
        falloff: 0.6,
    },
    Weapon {
        name: "Bazooka",
        kind: WeaponKind::Launcher,
        damage: 120.0,
        rate: 0.7,
        auto: false,
        clip: 1,
        reload: 2.6,
        pellets: 1,
        spread: 0.0,
        range: 900.0,
        speed: 520.0,
        knockback: 300.0,
        sever: 0.6,
        explosive: 90.0,
        ammo: Ammo::Rockets,
        reach: 0.0,
        ricochet: 0,
        pierce: 0,
        wall_pierce: 0,
        falloff: 1.0,
    },
    Weapon {
        name: "Side-by-Side",
        kind: WeaponKind::Sxs,
        damage: 17.0,
        rate: 2.6,
        auto: false,
        clip: 2,
        reload: 1.9,
        pellets: 9,
        spread: 0.24,
        range: 300.0,
        speed: 800.0,
        knockback: 180.0,
        sever: 0.18,
        explosive: 0.0,
        ammo: Ammo::Shells,
        reach: 0.0,
        // Buckshot ricochets off walls, losing bite on each bounce.
        ricochet: 1,
        pierce: 0,
        wall_pierce: 0,
        falloff: 0.7,
    },
];

pub fn weapon(i: usize) -> &'static Weapon {
    &WEAPONS[i.min(WEAPONS.len() - 1)]
}
